"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Badge, Button, Dialog, StatePanel } from "../../../components/ui";
import { ApiClientError, apiFetch } from "../../../lib/api-client";

type Project = { id: number; name: string };
type QueueItem = { id: string | number; project_id?: number; issue_id?: string; target_type?: string; target_field?: string; comment_id?: string | null; review_status?: string; source_text?: string | null; ai_draft?: string | null; reviewed_text?: string | null; provider_error?: string | null; provider?: string | null; model_or_command?: string | null; updated_at?: string };
function messageFor(error: unknown, fallback: string) { return error instanceof ApiClientError ? error.message : error instanceof Error ? error.message : fallback; }
function clip(value: unknown) { return String(value || "—").slice(0, 220); }

export default function TranslationQueuePage() {
  const router = useRouter(); const params = useSearchParams();
  const projectId = params.get("project_id") || ""; const issueId = params.get("issue_id") || ""; const status = params.get("review_status") || "";
  const [projects, setProjects] = useState<Project[]>([]); const [items, setItems] = useState<QueueItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [actionError, setActionError] = useState(""); const [actionFeedback, setActionFeedback] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [editItem, setEditItem] = useState<QueueItem | null>(null); const [editText, setEditText] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const listed = await apiFetch<Project[]>("/api/v1/projects"); setProjects(listed); const query = new URLSearchParams(); if (projectId) query.set("project_id", projectId); if (issueId) query.set("issue_id", issueId); if (status) query.set("review_status", status); setItems(await apiFetch<QueueItem[]>(`/api/v1/translation-queue${query.toString() ? `?${query}` : ""}`)); } catch (failure) { setError(messageFor(failure, "Translation Queue could not be loaded.")); } finally { setLoading(false); } }, [issueId, projectId, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); const refresh = () => void load(); window.addEventListener("cis-global-refresh", refresh); return () => { window.clearTimeout(timer); window.removeEventListener("cis-global-refresh", refresh); }; }, [load]);
  function setFilter(name: string, value: string) { const next = new URLSearchParams(params.toString()); if (value) next.set(name, value); else next.delete(name); router.push(`/translation-queue${next.toString() ? `?${next}` : ""}`); }
  async function action(item: QueueItem, kind: "approve" | "reject" | "retranslate" | "manual-edit") { const key = `${kind}:${item.id}`; setBusy(key); setActionError(""); setActionFeedback(""); try { let response: { reused?: boolean; job?: { id?: string } } = {}; if (kind === "manual-edit") { await apiFetch(`/api/v1/translation-queue/${item.id}/manual-edit`, { method: "POST", body: { reviewed_text: editText, review_notes: "translation-queue" } }); setEditItem(null); } else { response = await apiFetch<{ reused?: boolean; job?: { id?: string } }>(`/api/v1/translation-queue/${item.id}/${kind}`, { method: "POST", body: { review_notes: "translation-queue" } }); } if (kind === "retranslate") setActionFeedback(response.reused ? `Retranslate job already active; reused${response.job?.id ? ` (${response.job.id})` : ""}.` : `Retranslate job queued${response.job?.id ? ` (${response.job.id})` : ""}.`); await load(); } catch (failure) { setActionError(messageFor(failure, "Translation action failed.")); } finally { setBusy(null); } }
  if (loading) return <section className="mx-auto max-w-7xl"><StatePanel title="Loading Translation Queue" message="Reading current drafts and review state…" /></section>;
  if (error) return <section className="mx-auto max-w-7xl"><StatePanel title="Translation Queue unavailable" message={error} action={<Button onClick={() => void load()} variant="primary">Retry</Button>} /></section>;
  return <section className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow font-mono text-xs uppercase tracking-[0.2em]">TRANSLATION</p><h1 className="text-primary mt-3 text-3xl font-semibold tracking-tight">Review queue</h1><p className="text-secondary mt-2 text-sm">Keep AI draft and human-reviewed text visible as separate evidence.</p></div><Badge>{items.length} items</Badge></div>
    {actionError ? <p className="error-panel rounded-lg border p-3 text-sm" role="alert">{actionError}</p> : null}{actionFeedback ? <p className="warning-panel rounded-lg border p-3 text-sm" role="status">{actionFeedback}</p> : null}
    <section className="surface rounded-xl border p-5" aria-label="Translation queue filters"><div className="grid gap-4 md:grid-cols-3"><label className="text-secondary text-sm">Project<select aria-label="Queue project" className="field-control mt-2 w-full rounded-lg border px-3 py-2" onChange={(event) => setFilter("project_id", event.target.value)} value={projectId}><option value="">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="text-secondary text-sm">Issue ID<input aria-label="Queue issue" className="field-control mt-2 w-full rounded-lg border px-3 py-2" onChange={(event) => setFilter("issue_id", event.target.value)} value={issueId} placeholder="Optional issue id" /></label><label className="text-secondary text-sm">Review status<select aria-label="Queue status" className="field-control mt-2 w-full rounded-lg border px-3 py-2" onChange={(event) => setFilter("review_status", event.target.value)} value={status}><option value="">All statuses</option>{["pending", "ai_draft", "approved", "edited", "rejected"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div></section>
    <section className="surface rounded-xl border" aria-labelledby="queue-list-heading"><div className="border-b p-5" style={{ borderColor: "var(--border)" }}><h2 className="text-primary text-lg font-semibold" id="queue-list-heading">Queue items</h2><p className="text-secondary mt-1 text-sm">Provider errors and review lifecycle stay attached to each row.</p></div>{items.length ? <div className="overflow-x-auto"><table className="data-table translation-queue-table w-full min-w-[1180px] text-left text-sm"><thead className="text-subtle border-b text-xs uppercase tracking-wide"><tr><th>ID</th><th>Issue</th><th>Target</th><th>Status</th><th>Source</th><th>AI draft</th><th>Reviewed</th><th>Provider</th><th>Actions</th></tr></thead><tbody>{items.map((item) => { const hasDraft = Boolean(item.ai_draft); const canApprove = hasDraft && !["approved", "rejected"].includes(item.review_status || ""); return <tr key={String(item.id)}><td className="text-primary font-mono text-xs">{item.id}</td><td>{item.issue_id ? <Link className="text-primary underline" href={`/cis-issues/${encodeURIComponent(item.issue_id)}`}>{item.issue_id}</Link> : "—"}</td><td className="text-secondary">{item.target_type || "issue"} · {item.target_field || item.comment_id || "—"}</td><td><Badge tone={item.review_status === "approved" || item.review_status === "edited" ? "good" : item.review_status === "rejected" ? "warn" : "neutral"}>{item.review_status || "pending"}</Badge></td><td className="translation-queue-text text-secondary">{clip(item.source_text)}</td><td className="translation-queue-text text-secondary">{clip(item.ai_draft)}{item.provider_error ? <span className="error-panel mt-1 block rounded border p-1 text-xs">{item.provider_error}</span> : null}</td><td className="translation-queue-text text-secondary">{clip(item.reviewed_text)}</td><td className="translation-queue-provider text-subtle text-xs">{item.provider || "—"}<br />{item.model_or_command || ""}</td><td><div className="translation-queue-actions flex flex-wrap gap-2"><Button disabled={busy !== null || !canApprove} onClick={() => void action(item, "approve")} variant="primary">{busy === `approve:${item.id}` ? "Saving…" : "Approve"}</Button><Button disabled={busy !== null || !hasDraft} onClick={() => { setEditItem(item); setEditText(item.reviewed_text || item.ai_draft || ""); }} variant="secondary">Edit</Button><Button disabled={busy !== null} onClick={() => void action(item, "reject")} variant="secondary">Reject</Button><Button disabled={busy !== null} onClick={() => void action(item, "retranslate")} variant="secondary">{busy === `retranslate:${item.id}` ? "Queueing…" : "Retranslate"}</Button></div></td></tr>; })}</tbody></table></div> : <div className="p-8"><p className="text-primary font-semibold">No translation queue items</p><p className="text-secondary mt-2 text-sm">Adjust filters or translate an issue from the Issue Editor.</p></div>}</section>
    {editItem ? <Dialog className="max-w-2xl rounded-xl p-5" label="Edit reviewed translation" onClose={() => setEditItem(null)}><div className="flex items-center justify-between gap-3"><div><h2 className="text-primary text-lg font-semibold">Edit reviewed text</h2><p className="text-secondary mt-1 text-xs">Queue item {editItem.id}</p></div><Button onClick={() => setEditItem(null)} variant="secondary">Close</Button></div><textarea aria-label="Reviewed text" className="field-control mt-4 min-h-36 w-full rounded-lg border px-3 py-2" onChange={(event) => setEditText(event.target.value)} value={editText} /><div className="mt-4 flex justify-end gap-2"><Button onClick={() => setEditItem(null)} variant="secondary">Cancel</Button><Button disabled={!editText.trim() || Boolean(busy)} onClick={() => void action(editItem, "manual-edit")} variant="primary">{busy === `manual-edit:${editItem.id}` ? "Saving…" : "Save reviewed text"}</Button></div></Dialog> : null}
  </section>;
}
